[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.21'
fuzz_runs = 5000
verbosity=2
gas_reports=['*']
optimizer_runs = 100_000
#via_ir = true

##fuzz_max_global_rejects = 2_000_000
#optimizer_runs = 13_377
